### ISSUE TITLE
Cannot find module 'html-webpack-plugin'

### ISSUE THREAD

**Issue by bitwerk** [survivejs/webpack#100]
The solution was to run `npm i html-webpack-plugin --save-dev` before building with webpack.

**OS:** Windows 10
**Node:** v6.3.1
**Book page:** 6 (at 'If you execute node_modules/.bin/webpack, you should see output ...)
**Stacktrace:**

```
C:\work\webpack-demo>node_modules\.bin\webpack.cmd
module.js:442
    throw err;
    ^

Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\work\webpack-demo\webpack.config.js:2:27)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
C:\work\webpack-demo>node_modules\.bin\webpack.cmd
module.js:442
    throw err;
    ^

Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\work\webpack-demo\webpack.config.js:2:27)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by bebraw** [comment]
Hi,

There's a snippet like `To keep things simple to maintain, we'll be using html-webpack-plugin to generate an index.html for our application. html-webpack-plugin wires up the generated assets with it. Install it in the project:` just before `If you execute node_modules/.bin/webpack, you should see output`.

Is it possible you missed that?

Thanks for the report. 👍

**Comment by bebraw** [comment]
Time to close. Thanks!

**Comment by SAWC98** [comment]
same, I'm also following this error but not understanding how to resolve.

**Comment by bebraw** [comment]
@SAWC98 Can you link me to your project? It's important to have the plugin installed.

**Comment by keshav123ram** [comment]
Run below commond it will work 100%,i was facing same issue got resolve it.
npm install html-webpack-plugin
